INSERT INTO [AdvertCategories] ([Name],[ParentCategoryId],[Active] ) VALUES (N'Datortehnika', NULL, 1);
INSERT INTO [AdvertCategories] ([Name],[ParentCategoryId],[Active] ) VALUES (N'Portatīvie datori', 1, 1);
INSERT INTO [AdvertCategories] ([Name],[ParentCategoryId],[Active] ) VALUES (N'Personālie datori', 1, 1);
INSERT INTO [AdvertCategories] ([Name],[ParentCategoryId],[Active] ) VALUES (N'Monitori', 1, 1);
INSERT INTO [AdvertCategories] ([Name],[ParentCategoryId],[Active] ) VALUES (N'Datoru komponentes', NULL, 1);
INSERT INTO [AdvertCategories] ([Name],[ParentCategoryId],[Active] ) VALUES (N'CPU', 5, 1);
INSERT INTO [AdvertCategories] ([Name],[ParentCategoryId],[Active] ) VALUES (N'GPU', 5, 1);
INSERT INTO [AdvertCategories] ([Name],[ParentCategoryId],[Active] ) VALUES (N'RAM', 5, 1);
INSERT INTO [AdvertCategories] ([Name],[ParentCategoryId],[Active] ) VALUES (N'Sadzīves tehnika', NULL, 1);
INSERT INTO [AdvertCategories] ([Name],[ParentCategoryId],[Active] ) VALUES (N'Mazā sadzīves tehnika', 9, 1);
INSERT INTO [AdvertCategories] ([Name],[ParentCategoryId],[Active] ) VALUES (N'Lielā sadzīves tehnika', 9, 1);